### ISSUE TITLE
Doesn't work "line numbering"

### ISSUE THREAD

**Issue by Kostelano** [ahotzler/plg_content_prismsyntaxhighlighter#2]
Good day! After updating the plugin to version 1.1.7, "line numbering" does not work. The code has indents, numbering is not displayed.

The problem on all styles of the plugin.

Joomla 3.9.13
PHP 7.2

**Comment by ahotzler** [comment]
Hi, i will check this.

**Comment by ahotzler** [comment]
Hello, thank you for your hints and collaboration. The numbering should work now and I took over your changes.
Can you also test and give me feedback?

**Comment by Kostelano** [comment]
Yes, of course, I will test and tomorrow I will unsubscribe here.

**Comment by Kostelano** [comment]
I checked on all styles, everything is in order, everything works. Thank you very much for the fix.
https://github.com/ahotzler/plg_content_prismsyntaxhighlighter/commit/90dfe9b5b594654a7b182297830cb5026911859a
https://github.com/ahotzler/plg_content_prismsyntaxhighlighter/commit/0abdf7a02adfb3108cde6c69a31e8489cfadd372
